# Generated by Django 4.1.7 on 2023-05-19 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='slug',
        ),
    ]
