# Generated by Django 4.1.7 on 2023-06-19 10:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0006_room_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='members',
            field=models.ManyToManyField(default=True, related_name='rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
