# Generated by Django 5.0.6 on 2024-06-17 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0011_alter_message_open_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='open_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='room.open_room'),
        ),
    ]
